sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server
  - memcached

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then pecl install apcu; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then pecl install -f igbinary; fi;
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source "$PREFER_LOWEST"

script:
  - php -d 'apc.enable_cli=1' ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
